using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ProtoHandlerGen
{
    public sealed partial class ProtoHandlerGenerator
    {
        static void Emit(SourceProductionContext context, PresenterModel model)
        {
            var isEventOnly = model.CommandTypeFullName == null;
            var isCommandOnly = model.EventTypeFullName == null;

            // Diagnostics: unhandled cases (command-only or command+event)
            if (!isEventOnly)
            {
                foreach (var unhandled in model.UnhandledCases)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Descriptors.UnhandledOneofCase,
                        model.ClassLocation,
                        unhandled.CaseName,
                        model.CommandTypeFullName,
                        model.ClassName,
                        unhandled.CaseTypeFullName));
                }
            }

            // Diagnostics: PROTO002 - Handle method with unmatched parameter type
            if (!isEventOnly)
            {
                foreach (var unmatched in model.UnmatchedHandleMethods)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Descriptors.UnmatchedHandleMethod,
                        model.ClassLocation,
                        unmatched.MethodName,
                        model.ClassName,
                        unmatched.ParameterTypeFullName,
                        model.CommandTypeFullName));
                }
            }

            // Diagnostics: PROTO003 - Handle method in event-only presenter
            if (isEventOnly)
            {
                foreach (var unmatched in model.UnmatchedHandleMethods)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Descriptors.HandleMethodInEventOnly,
                        model.ClassLocation,
                        unmatched.MethodName,
                        model.ClassName));
                }
            }

            // Diagnostics: PROTO005 - Ambiguous routing path
            if (model.CommandRouteAmbiguity != null)
            {
                var parents = model.CommandRouteAmbiguity.Split(new[] { ", " }, System.StringSplitOptions.None);
                var first = parents.Length > 0 ? parents[0].Split('.').Last() : "";
                var second = parents.Length > 1 ? parents[1].Split('.').Last() : first;
                context.ReportDiagnostic(Diagnostic.Create(
                    Descriptors.AmbiguousRoute,
                    model.ClassLocation,
                    model.CommandTypeFullName,
                    model.CommandRouteAmbiguity,
                    first,
                    second));
            }
            if (model.EventRouteAmbiguity != null)
            {
                var parents = model.EventRouteAmbiguity.Split(new[] { ", " }, System.StringSplitOptions.None);
                var first = parents.Length > 0 ? parents[0].Split('.').Last() : "";
                var second = parents.Length > 1 ? parents[1].Split('.').Last() : first;
                context.ReportDiagnostic(Diagnostic.Create(
                    Descriptors.AmbiguousRoute,
                    model.ClassLocation,
                    model.EventTypeFullName,
                    model.EventRouteAmbiguity,
                    first,
                    second));
            }

            // Diagnostics: PROTO006 - Invalid route hint
            if (model.InvalidRouteHint != null)
            {
                var targetType = model.CommandRouteAmbiguity != null
                    ? model.CommandTypeFullName
                    : model.EventTypeFullName;
                var validParents = model.CommandRouteAmbiguity ?? model.EventRouteAmbiguity ?? "";
                context.ReportDiagnostic(Diagnostic.Create(
                    Descriptors.InvalidRouteHint,
                    model.ClassLocation,
                    model.InvalidRouteHint,
                    targetType,
                    validParents));
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.CodeDom.Compiler;");
            if (model.InfrastructureNamespace != null)
                sb.AppendLine($"using {model.InfrastructureNamespace};");
            sb.AppendLine("using Cortis;");
            sb.AppendLine("using R3;");
            sb.AppendLine("using VContainer;");
            sb.AppendLine("using VContainer.Unity;");
            if (model.Handlers.Any(h => h.IsAsync))
                sb.AppendLine("using Cysharp.Threading.Tasks;");
            sb.AppendLine();

            if (model.Namespace != null)
            {
                sb.AppendLine($"namespace {model.Namespace}");
                sb.AppendLine("{");
            }

            var indent = model.Namespace != null ? "    " : "";

            // Class declaration with interfaces
            sb.Append($"{indent}[GeneratedCode(\"ProtoHandlerGenerator\", \"1.0.0\")]");
            sb.AppendLine();
            sb.Append($"{indent}partial class {model.ClassName}");

            // Interface list
            var interfaces = new System.Collections.Generic.List<string>();
            if (!isEventOnly)
                interfaces.Add($"ICommandHandler<{model.CommandTypeFullName}>");
            interfaces.Add("IInitializable");
            interfaces.Add("IDisposable");
            sb.Append($" : {string.Join(", ", interfaces)}");

            sb.AppendLine();
            sb.AppendLine($"{indent}{{");

            var i2 = indent + "    ";
            var i3 = indent + "        ";

            // Fields
            if (!isEventOnly)
            {
                sb.AppendLine($"{i2}Binder _binder;");
            }
            sb.AppendLine($"{i2}IMessageGateway _gateway;");
            sb.AppendLine();

            // Method injection: bind command subscriptions
            var hasCommandRoute = !model.CommandRoute.IsDefaultOrEmpty;
            var hasEventRoute = !model.EventRoute.IsDefaultOrEmpty;

            sb.AppendLine($"{i2}[Inject]");
            sb.AppendLine($"{i2}void InjectBindings(IMessageGateway gateway)");
            sb.AppendLine($"{i2}{{");
            sb.AppendLine($"{i3}_gateway = gateway;");
            if (!isEventOnly)
            {
                if (hasCommandRoute)
                {
                    EmitRoutedBinding(sb, i3, model);
                }
                else
                {
                    sb.AppendLine($"{i3}_binder = MessageBinding.Bind<{model.CommandTypeFullName}>(this, gateway);");
                }
            }
            sb.AppendLine($"{i2}}}");
            sb.AppendLine();

            // ICommandHandler.Handle (not generated for event-only)
            if (!isEventOnly)
            {
                sb.AppendLine($"{i2}public void Handle({model.CommandTypeFullName} command)");
                sb.AppendLine($"{i2}{{");
                sb.AppendLine($"{i3}switch (command.{model.CommandOneofPropertyName})");
                sb.AppendLine($"{i3}{{");
                foreach (var handler in model.Handlers)
                {
                    sb.AppendLine($"{i3}    case {model.CommandOneofEnumFullName}.{handler.CaseName}:");
                    if (handler.IsAsync)
                        sb.AppendLine($"{i3}        {handler.MethodName}(command.{handler.CaseName}).Forget();");
                    else
                        sb.AppendLine($"{i3}        {handler.MethodName}(command.{handler.CaseName});");
                    sb.AppendLine($"{i3}        break;");
                }
                sb.AppendLine($"{i3}    default:");
                sb.AppendLine($"{i3}        break;");
                sb.AppendLine($"{i3}}}");
                sb.AppendLine($"{i2}}}");
                sb.AppendLine();
            }

            // Initialize
            sb.AppendLine($"{i2}public void Initialize()");
            sb.AppendLine($"{i2}{{");
            sb.AppendLine($"{i3}OnInitialize();");
            sb.AppendLine($"{i2}}}");
            sb.AppendLine();
            sb.AppendLine($"{i2}private partial void OnInitialize();");
            sb.AppendLine();

            // SendEvent (generated when event type exists)
            if (!isCommandOnly)
            {
                EmitSendEvent(sb, i2, model, hasEventRoute);
                sb.AppendLine();
            }

            // Dispose
            sb.AppendLine($"{i2}public void Dispose()");
            sb.AppendLine($"{i2}{{");
            if (!isEventOnly)
            {
                sb.AppendLine($"{i3}_binder?.Dispose();");
            }
            sb.AppendLine($"{i3}OnDispose();");
            sb.AppendLine($"{i2}}}");
            sb.AppendLine();
            sb.AppendLine($"{i2}private partial void OnDispose();");
            sb.AppendLine();

            // Register
            sb.AppendLine($"{i2}public static RegistrationBuilder Register(IContainerBuilder builder, Lifetime lifetime)");
            sb.AppendLine($"{i2}{{");
            sb.Append($"{i3}return builder.Register<{model.ClassName}>(lifetime)");
            sb.AppendLine();
            if (!isEventOnly)
            {
                sb.AppendLine($"{i3}    .As<ICommandHandler<{model.CommandTypeFullName}>>()");
            }
            sb.AppendLine($"{i3}    .As<IInitializable>()");
            sb.AppendLine($"{i3}    .As<IDisposable>();");
            sb.AppendLine($"{i2}}}");

            sb.AppendLine($"{indent}}}");

            if (model.Namespace != null)
            {
                sb.AppendLine("}");
            }

            context.AddSource($"{model.ClassName}.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        static void EmitRoutedBinding(
            StringBuilder sb,
            string indent,
            PresenterModel model)
        {
            var i4 = indent + "    ";

            var rootCmdType = model.CommandRoute[0].ParentTypeFullName;
            sb.AppendLine($"{indent}_binder = MessageBinding.BindRouted<{rootCmdType}, {model.CommandTypeFullName}>(this, gateway,");
            EmitUnwrapLambda(sb, i4, model.CommandRoute);
            sb.AppendLine(");");
        }

        /// <summary>
        /// SendEvent メソッドを生成する。
        /// ルーティングなし: _gateway.Send(Google.Protobuf.WellKnownTypes.Any.Pack(evt))
        /// ルーティングあり: inner → root にラップしてから送信
        /// </summary>
        static void EmitSendEvent(
            StringBuilder sb,
            string indent,
            PresenterModel model,
            bool hasEventRoute)
        {
            var i3 = indent + "    ";
            if (!hasEventRoute)
            {
                sb.AppendLine($"{indent}void SendEvent({model.EventTypeFullName} evt) => _gateway.Send(Google.Protobuf.WellKnownTypes.Any.Pack(evt));");
            }
            else
            {
                sb.AppendLine($"{indent}void SendEvent({model.EventTypeFullName} evt)");
                sb.AppendLine($"{indent}{{");
                sb.Append($"{i3}var wrapped = ");
                // Build inline wrap expression (same logic as EmitWrapLambda but inline)
                for (int i = 0; i < model.EventRoute.Length; i++)
                {
                    var seg = model.EventRoute[i];
                    sb.Append($"new {seg.ParentTypeFullName} {{ {seg.PropertyName} = ");
                }
                sb.Append("evt");
                for (int i = 0; i < model.EventRoute.Length; i++)
                {
                    sb.Append(" }");
                }
                sb.AppendLine(";");
                sb.AppendLine($"{i3}_gateway.Send(Google.Protobuf.WellKnownTypes.Any.Pack(wrapped));");
                sb.AppendLine($"{indent}}}");
            }
        }

        /// <summary>
        /// Command の unwrap ラムダを生成する。
        /// 1段: root => root.ActionCase == X.PlayerAction ? root.PlayerAction : null
        /// 多段: root => { if (...) return null; var _r0 = ...; ... return _rN.Inner; }
        /// </summary>
        static void EmitUnwrapLambda(StringBuilder sb, string indent, ImmutableArray<RouteSegment> route)
        {
            if (route.Length == 1)
            {
                var seg = route[0];
                sb.Append($"{indent}root => root.{seg.OneofCasePropertyName} == {seg.OneofEnumFullName}.{seg.PropertyName} ? root.{seg.PropertyName} : null");
            }
            else
            {
                sb.AppendLine($"{indent}root =>");
                sb.AppendLine($"{indent}{{");
                var varName = "root";
                for (int i = 0; i < route.Length; i++)
                {
                    var seg = route[i];
                    sb.AppendLine($"{indent}    if ({varName}.{seg.OneofCasePropertyName} != {seg.OneofEnumFullName}.{seg.PropertyName}) return null;");
                    if (i < route.Length - 1)
                    {
                        var nextVar = $"_r{i}";
                        sb.AppendLine($"{indent}    var {nextVar} = {varName}.{seg.PropertyName};");
                        varName = nextVar;
                    }
                    else
                    {
                        sb.AppendLine($"{indent}    return {varName}.{seg.PropertyName};");
                    }
                }
                sb.Append($"{indent}}}");
            }
        }

    }
}
