using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ProtoHandlerGen
{
    public sealed partial class ProtoHandlerGenerator
    {
        static void Emit(SourceProductionContext context, PresenterModel model)
        {
            var isEventOnly = model.CommandTypeFullName == null;
            var isCommandOnly = model.EventTypeFullName == null;

            // Diagnostics: unhandled cases (command-only or command+event)
            if (!isEventOnly)
            {
                foreach (var unhandled in model.UnhandledCases)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Descriptors.UnhandledOneofCase,
                        model.ClassLocation,
                        unhandled.CaseName,
                        model.CommandTypeFullName,
                        model.ClassName));
                }
            }

            // Diagnostics: PROTO002 - Handle method with unmatched parameter type
            if (!isEventOnly)
            {
                foreach (var unmatched in model.UnmatchedHandleMethods)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Descriptors.UnmatchedHandleMethod,
                        model.ClassLocation,
                        unmatched.MethodName,
                        model.ClassName,
                        unmatched.ParameterTypeFullName,
                        model.CommandTypeFullName));
                }
            }

            // Diagnostics: PROTO003 - Handle method in event-only presenter
            if (isEventOnly)
            {
                foreach (var unmatched in model.UnmatchedHandleMethods)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Descriptors.HandleMethodInEventOnly,
                        model.ClassLocation,
                        unmatched.MethodName,
                        model.ClassName));
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.CodeDom.Compiler;");
            if (model.InfrastructureNamespace != null)
                sb.AppendLine($"using {model.InfrastructureNamespace};");
            sb.AppendLine("using Cortis;");
            sb.AppendLine("using R3;");
            sb.AppendLine("using VContainer;");
            sb.AppendLine("using VContainer.Unity;");
            if (model.Handlers.Any(h => h.IsAsync))
                sb.AppendLine("using Cysharp.Threading.Tasks;");
            sb.AppendLine();

            if (model.Namespace != null)
            {
                sb.AppendLine($"namespace {model.Namespace}");
                sb.AppendLine("{");
            }

            var indent = model.Namespace != null ? "    " : "";

            // Class declaration with interfaces
            sb.Append($"{indent}[GeneratedCode(\"ProtoHandlerGenerator\", \"0.1.0\")]");
            sb.AppendLine();
            sb.Append($"{indent}partial class {model.ClassName}");

            // Interface list
            var interfaces = new System.Collections.Generic.List<string>();
            if (!isEventOnly)
                interfaces.Add($"ICommandHandler<{model.CommandTypeFullName}>");
            if (!isCommandOnly)
                interfaces.Add($"IEventSource<{model.EventTypeFullName}>");
            interfaces.Add("IInitializable");
            interfaces.Add("IDisposable");
            sb.Append($" : {string.Join(", ", interfaces)}");

            sb.AppendLine();
            sb.AppendLine($"{indent}{{");

            var i2 = indent + "    ";
            var i3 = indent + "        ";

            // Fields
            sb.AppendLine($"{i2}Binder _binder;");
            if (!isCommandOnly)
            {
                sb.AppendLine($"{i2}readonly Subject<{model.EventTypeFullName}> _events = new();");
            }
            sb.AppendLine();

            // Method injection: bind command/event subscriptions
            sb.AppendLine($"{i2}[Inject]");
            sb.AppendLine($"{i2}void InjectBindings(IMessageGateway gateway)");
            sb.AppendLine($"{i2}{{");
            if (isEventOnly)
            {
                sb.AppendLine($"{i3}_binder = MessageBinding.Bind<{model.EventTypeFullName}>(this, gateway);");
            }
            else if (!isCommandOnly)
            {
                sb.AppendLine($"{i3}_binder = MessageBinding.Bind<{model.CommandTypeFullName}, {model.EventTypeFullName}>(this, this, gateway);");
            }
            else
            {
                sb.AppendLine($"{i3}_binder = MessageBinding.Bind<{model.CommandTypeFullName}>(this, gateway);");
            }
            sb.AppendLine($"{i2}}}");
            sb.AppendLine();

            // ICommandHandler.Handle (not generated for event-only)
            if (!isEventOnly)
            {
                sb.AppendLine($"{i2}public void Handle({model.CommandTypeFullName} command)");
                sb.AppendLine($"{i2}{{");
                sb.AppendLine($"{i3}switch (command.{model.CommandOneofPropertyName})");
                sb.AppendLine($"{i3}{{");
                foreach (var handler in model.Handlers)
                {
                    sb.AppendLine($"{i3}    case {model.CommandOneofEnumFullName}.{handler.CaseName}:");
                    if (handler.IsAsync)
                        sb.AppendLine($"{i3}        {handler.MethodName}(command.{handler.CaseName}).Forget();");
                    else
                        sb.AppendLine($"{i3}        {handler.MethodName}(command.{handler.CaseName});");
                    sb.AppendLine($"{i3}        break;");
                }
                sb.AppendLine($"{i3}    default:");
                sb.AppendLine($"{i3}        break;");
                sb.AppendLine($"{i3}}}");
                sb.AppendLine($"{i2}}}");
                sb.AppendLine();
            }

            // IEventSource.Events
            if (!isCommandOnly)
            {
                sb.AppendLine($"{i2}Observable<{model.EventTypeFullName}> IEventSource<{model.EventTypeFullName}>.Events => _events;");
                sb.AppendLine();
            }

            // Initialize
            sb.AppendLine($"{i2}public void Initialize()");
            sb.AppendLine($"{i2}{{");
            sb.AppendLine($"{i3}OnInitialize();");
            sb.AppendLine($"{i2}}}");
            sb.AppendLine();
            sb.AppendLine($"{i2}private partial void OnInitialize();");
            sb.AppendLine();

            // DispatchEvent overloads (not generated for command-only)
            if (!isCommandOnly && model.EventCases.IsEmpty)
            {
                // Non-oneof event type: single pass-through DispatchEvent
                var dispatchAccess = model.IsSealed ? "void" : "protected void";
                sb.AppendLine($"{i2}{dispatchAccess} DispatchEvent({model.EventTypeFullName} value)");
                sb.AppendLine($"{i2}{{");
                sb.AppendLine($"{i3}_events.OnNext(value);");
                sb.AppendLine($"{i2}}}");
                sb.AppendLine();
            }
            else if (!isCommandOnly)
            {
                // Oneof event type: one DispatchEvent per case
                foreach (var eventCase in model.EventCases)
                {
                    var dispatchAccess = model.IsSealed ? "void" : "protected void";
                    sb.AppendLine($"{i2}{dispatchAccess} DispatchEvent({eventCase.CaseTypeFullName} value)");
                    sb.AppendLine($"{i2}{{");
                    sb.AppendLine($"{i3}_events.OnNext(new {model.EventTypeFullName} {{ {eventCase.CaseName} = value }});");
                    sb.AppendLine($"{i2}}}");
                    sb.AppendLine();
                }
            }

            // Dispose
            sb.AppendLine($"{i2}public void Dispose()");
            sb.AppendLine($"{i2}{{");
            sb.AppendLine($"{i3}_binder?.Dispose();");
            if (!isCommandOnly)
            {
                sb.AppendLine($"{i3}_events.Dispose();");
            }
            sb.AppendLine($"{i3}OnDispose();");
            sb.AppendLine($"{i2}}}");
            sb.AppendLine();
            sb.AppendLine($"{i2}private partial void OnDispose();");
            sb.AppendLine();

            // Register
            sb.AppendLine($"{i2}public static void Register(IContainerBuilder builder, Lifetime lifetime)");
            sb.AppendLine($"{i2}{{");
            sb.Append($"{i3}builder.Register<{model.ClassName}>(lifetime)");
            sb.AppendLine();
            if (!isEventOnly)
            {
                sb.AppendLine($"{i3}    .As<ICommandHandler<{model.CommandTypeFullName}>>()");
            }
            if (!isCommandOnly)
            {
                sb.AppendLine($"{i3}    .As<IEventSource<{model.EventTypeFullName}>>()");
            }
            sb.AppendLine($"{i3}    .As<IInitializable>()");
            sb.AppendLine($"{i3}    .As<IDisposable>();");
            sb.AppendLine($"{i2}}}");

            sb.AppendLine($"{indent}}}");

            if (model.Namespace != null)
            {
                sb.AppendLine("}");
            }

            context.AddSource($"{model.ClassName}.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}
